os: linux
dist: bionic
language: c

before_install:
  - sudo apt-get update
  - sudo apt-get -y install gcc-multilib build-essential gpp

git:
  submodules: false
  depth: 3

install:
  - wget https://github.com/vipoo/z88dk/releases/download/v2.0.0-dino.3/z88dk-v2.0.0-dino.3.tar.gz
  - mkdir -p z88dk
  - tar -xzf z88dk-v2.0.0-dino.3.tar.gz -C ./z88dk/
  - wget https://github.com/vipoo/cpm/releases/download/v0.0.7/cpm-v0.0.7.tar.gz
  - mkdir -p cpm
  - tar -xzf cpm-v0.0.7.tar.gz -C ./cpm

before_script:
  - export PATH=`pwd`/cpm/bin:$PATH
  - export PATH=`pwd`/z88dk/bin:$PATH
  - export ZCCCFG=`pwd`/z88dk/lib/config

script:
  - make all VERSION=$TRAVIS_TAG
  - make test VERSION=$TRAVIS_TAG

# deploy:
#   provider: releases
#   api_key:
#     secure: ""
#   file: chip8.com
#   skip_cleanup: true
#   on:
#     tags: true

notifications:
  email: false
