
	PUBLIC	_hbCioIn, _hbCioIst, _hbCioOut

	SECTION CODE

BF_CIO		EQU	$00
BF_CIOIN	EQU	BF_CIO + 0	; CHARACTER INPUT
BF_CIOOUT	EQU	BF_CIO + 1	; CHARACTER OUTPUT
BF_CIOIST	EQU	BF_CIO + 2	; CHARACTER INPUT STATUS
BF_CIOOST	EQU	BF_CIO + 3	; CHARACTER OUTPUT STATUS
BF_CIOINIT	EQU	BF_CIO + 4	; INIT/RESET DEVICE/LINE CONFIG
BF_CIOQUERY	EQU	BF_CIO + 5	; REPORT DEVICE/LINE CONFIG
BF_CIODEVICE	EQU	BF_CIO + 6	; REPORT DEVICE INFO

	;extern byte hbCioIn(byte driver, char* result);
_hbCioIn:
	PUSH	IX
	LD	IX, 4			; REFERENCE C ARGS ON STACK
	ADD	IX, SP
	LD	B, BF_CIOIN
  	LD 	C, (IX + 0)		; DRIVER INDEX
	RST	08
	LD	L, A			; RETURN SUCCESS/FAIL
	LD	C, (IX + 1)		; WRITE CHAR TO *result
	LD	B, (IX + 2)
	LD	A, E
	LD	(BC), A
	POP	IX
	RET

	;extern byte hbCioIst(byte driver) __z88dk_fastcall;
_hbCioIst:
	PUSH	IX
	LD	B, BF_CIOIST
  	LD 	C, L			; DRIVER INDEX
	RST	08
	LD	L, A			; RETURN SUCCESS/FAIL
	POP	IX
	RET

	; extern byte hbCioOut(byte, char);
_hbCioOut:
	push	ix
	LD	HL, 4			; REFERENCE C ARGS ON STACK
	ADD	HL, SP
	LD	B, BF_CIOOUT
  	LD 	C, (HL)			; DRIVER INDEX
	INC	HL
	LD	E, (HL)			; CHAR TO WRITE
	RST	08
	LD	L, A			; RETURN SUCCESS/FAIL
	pop	ix
	RET


	SECTION IGNORE
