
	PUBLIC	_hbSysGetTimer

	SECTION CODE

BF_SYS		EQU	$F0
BF_SYSRESET	EQU	BF_SYS + 0	; SOFT RESET HBIOS
BF_SYSVER	EQU	BF_SYS + 1	; GET HBIOS VERSION
BF_SYSSETBNK	EQU	BF_SYS + 2	; SET CURRENT BANK
BF_SYSGETBNK	EQU	BF_SYS + 3	; GET CURRENT BANK
BF_SYSSETCPY	EQU	BF_SYS + 4	; BANK MEMORY COPY SETUP
BF_SYSBNKCPY	EQU	BF_SYS + 5	; BANK MEMORY COPY
BF_SYSALLOC	EQU	BF_SYS + 6	; ALLOC HBIOS HEAP MEMORY
BF_SYSFREE	EQU	BF_SYS + 7	; FREE HBIOS HEAP MEMORY
BF_SYSGET	EQU	BF_SYS + 8	; GET HBIOS INFO
BF_SYSSET	EQU	BF_SYS + 9	; SET HBIOS PARAMETERS
BF_SYSPEEK	EQU	BF_SYS + 10	; GET A BYTE VALUE FROM ALT BANK
BF_SYSPOKE	EQU	BF_SYS + 11	; SET A BYTE VALUE IN ALT BANK
BF_SYSINT	EQU	BF_SYS + 12	; MANAGE INTERRUPT VECTORS
;
BF_SYSRES_INT		EQU	$00	; RESET HBIOS INTERNAL
BF_SYSRES_WARM		EQU	$01	; WARM START (RESTART BOOT LOADER)
BF_SYSRES_COLD		EQU	$02	; COLD START
;
BF_SYSGET_CIOCNT	EQU	$00	; GET CHAR UNIT COUNT
BF_SYSGET_CIOFN		EQU	$01	; GET CIO UNIT FN/DATA ADR
BF_SYSGET_DIOCNT	EQU	$10	; GET DISK UNIT COUNT
BF_SYSGET_DIOFN		EQU	$11	; GET DIO UNIT FN/DATA ADR
BF_SYSGET_RTCCNT	EQU	$20	; GET RTC UNIT COUNT
BF_SYSGET_VDACNT	EQU	$40	; GET VDA UNIT COUNT
BF_SYSGET_VDAFN		EQU	$41	; GET VDA UNIT FN/DATA ADR
BF_SYSGET_SNDCNT	EQU	$50	; GET VDA UNIT COUNT
BF_SYSGET_SNDFN		EQU	$51	; GET SND UNIT FN/DATA ADR
BF_SYSGET_TIMER		EQU	$D0	; GET CURRENT TIMER VALUE
BF_SYSGET_SECS		EQU	$D1	; GET CURRENT SECONDS VALUE
BF_SYSGET_BOOTINFO	EQU	$E0	; GET BOOT INFORMATION
BF_SYSGET_CPUINFO	EQU	$F0	; GET CPU INFORMATION
BF_SYSGET_MEMINFO	EQU	$F1	; GET MEMORY CAPACTITY INFO
BF_SYSGET_BNKINFO	EQU	$F2	; GET BANK ASSIGNMENT INFO
;
BF_SYSSET_TIMER		EQU	$D0	; SET TIMER VALUE
BF_SYSSET_SECS		EQU	$D1	; SET SECONDS VALUE
BF_SYSSET_BOOTINFO	EQU	$E0	; SET BOOT INFORMATION
;
BF_SYSINT_INFO		EQU	$00	; GET INTERRUPT SYSTEM INFO
BF_SYSINT_GET		EQU	$10	; GET INT VECTOR ADDRESS
BF_SYSINT_SET		EQU	$20	; SET INT VECTOR ADDRESS

	;extern byte hbSysGetTimer(long* result) __z88dk_fastcall;
_hbSysGetTimer:
	PUSH	IX
	PUSH	HL
	LD	BC, 0xF8D0
	RST	08

	POP	BC

	PUSH	AF
	LD	A, L
	LD	(BC), A
	INC	BC
	LD	A, B
	LD	(BC), A
	INC	BC
	LD	A, E
	LD	(BC), A
	INC	BC
	LD	A, D
	LD	(BC), A
	POP	AF

	LD	L, A
	POP	IX
	RET

	SECTION IGNORE
